#!/bin/bash

# Script to export environment variables for Vercel dashboard
# Run this script and copy the output to Vercel's Environment Variables section

echo "=========================================="
echo "Vercel Environment Variables"
echo "=========================================="
echo ""
echo "Copy each variable below and paste into Vercel:"
echo ""
echo "1. NEXT_PUBLIC_SUPABASE_URL"
echo "   Value: https://vvgvhlswsiqpnpwlcxud.supabase.co"
echo ""
echo "2. NEXT_PUBLIC_SUPABASE_ANON_KEY"
echo "   Value: sb_publishable_HiwhxAUb3inMaBx_r8TZ6w_EvV2Cagz"
echo ""
echo "3. SUPABASE_SERVICE_ROLE_KEY"
echo "   Value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ2Z3ZobHN3c2lxcG5wd2xjeHVkIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2NTY4MDEwNCwiZXhwIjoyMDgxMjU2MTA0fQ.sL3SMqZCtgYSu3Eqq7KHwvjPqzcki2A6k60TXARddqo"
echo ""
echo "4. VERCEL_CRON_SECRET"
echo "   Value: pC7gF9xW2rQ81vNzb4KLMt6uYH0qSdVp"
echo ""
echo "5. DIGITALOCEAN_SPACES_ENDPOINT"
echo "   Value: https://my-wallet-passes.sfo3.digitaloceanspaces.com"
echo ""
echo "6. DIGITALOCEAN_SPACES_KEY"
echo "   Value: DO008MPWKAQLPXQEHCCJ"
echo ""
echo "7. DIGITALOCEAN_SPACES_SECRET"
echo "   Value: va8Z1494r4UcCu5YBc39j2boGoa6h13J+Ta+V8Obgcs"
echo ""
echo "8. ENCRYPTION_SECRET"
echo "   Value: pC7gF9xW2rQ81vNzb4KLMt6uYH0qSdVp"
echo ""
echo "=========================================="
echo ""
echo "Instructions:"
echo "1. Go to your Vercel project → Settings → Environment Variables"
echo "2. For each variable above:"
echo "   - Click 'Add New'"
echo "   - Paste the variable name (left side)"
echo "   - Paste the value (right side)"
echo "   - Select: Production, Preview, Development"
echo "   - Click 'Save'"
echo ""
echo "3. After adding all variables, redeploy your project"
echo ""

